package extract

import (
	"go/constant"
	"go/types"
	"io"
)

const model = `// Code generated by 'yaegi extract {{.ImportPath}}'. DO NOT EDIT.

{{.License}}

{{if .BuildTags}}// +build {{.BuildTags}}{{end}}

package {{.Dest}}

import (
{{- range $key, $value := .Imports }}
	{{- if $value}}
	"{{$key}}"
	{{- end}}
{{- end}}
{{- if or .Val .Typ }}
	"{{.ImportPath}}"
{{- end}}
	"reflect"
)

func init() {
	Symbols["{{.PkgName}}"] = map[string]reflect.Value{
		{{- if .Val}}
		// function, constant and variable definitions
		{{range $key, $value := .Val -}}
			{{- if $value.Addr -}}
				"{{$key}}": reflect.ValueOf(&{{$value.Name}}).Elem(),
			{{else -}}
				"{{$key}}": reflect.ValueOf({{$value.Name}}),
			{{end -}}
		{{end}}

		{{- end}}
		{{- if .Typ}}
		// type definitions
		{{range $key, $value := .Typ -}}
			"{{$key}}": reflect.ValueOf((*{{$value}})(nil)),
		{{end}}

		{{- end}}
		{{- if .Wrap}}
		// interface wrapper definitions
		{{range $key, $value := .Wrap -}}
			"_{{$key}}": reflect.ValueOf((*{{$value.Name}})(nil)),
		{{end}}
		{{- end}}
	}
}
{{range $key, $value := .Wrap -}}
	// {{$value.Name}} is an interface wrapper for {{$key}} type
	type {{$value.Name}} struct {
		IValue interface{}
		{{range $m := $value.Method -}}
		W{{$m.Name}} func{{$m.Param}} {{$m.Result}}
		{{end}}
	}
	{{range $m := $value.Method -}}
		func (W {{$value.Name}}) {{$m.Name}}{{$m.Param}} {{$m.Result}} {
			{{- if eq $m.Name "String"}}
			if W.WString == nil {
				return ""
			}
			{{end}}
			{{- $m.Ret}} W.W{{$m.Name}}{{$m.Arg -}}
		}
	{{end}}
{{end}}
`

type Val struct {
	Name string
	Addr bool
}

type Method struct {
	Name, Param, Result, Arg, Ret string
}

type Wrap struct {
	Name   string
	Method []Method
}

var restricted = map[string]bool{
	"osExit":        true,
	"osFindProcess": true,
	"logFatal":      true,
	"logFatalf":     true,
	"logFatalln":    true,
	"logLogger":     true,
	"logNew":        true,
}

func matchList(name string, list []string) (match bool, err error) {
	_ = "STUB: not implemented"
	return false, nil
}

type Extractor struct {
	Dest    string
	License string
	Exclude []string
	Include []string
	Tag     []string
}

func (e *Extractor) genContent(importPath string, p *types.Package) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func fixConst(name string, val constant.Value, imports map[string]bool) string {
	_ = "STUB: not implemented"
	return ""
}

//nolint:gocritic // Empty Fallthrough is expected.

func (e *Extractor) importPath(pkgIdent, importPath string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

func (e *Extractor) Extract(pkgIdent, importPath string, rw io.Writer) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

func GetMinor(part string) string { _ = "STUB: not implemented"; return "" }

const defaultMinorVersion = 22

func genBuildTags() (string, error) { _ = "STUB: not implemented"; return "", nil }

func isInStdlib(path string) bool { _ = "STUB: not implemented"; return false }
